"""Documentation page — what the system is and how it decides to answer or
decline. Reached from the demo via the top-right link.
"""
from __future__ import annotations

import os

import requests
import streamlit as st

from nav import demo_page

API = os.environ.get("API_URL", "http://localhost:8000")

MARK = (
    '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
    'stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'
    '<circle cx="12" cy="17.5" r="1.9" fill="currentColor" stroke="none"/>'
    '<path d="M8.4 13.9a5 5 0 0 1 7.2 0"/><path d="M5.8 11a9 9 0 0 1 12.4 0"/></svg>'
)

with st.container(key="topbar"):
    left, right = st.columns([3, 1], vertical_alignment="center")
    left.markdown(
        f'<div class="brand"><span class="brand__mark">{MARK}</span>'
        f'<span class="brand__name">Documentation</span></div>',
        unsafe_allow_html=True,
    )
    right.page_link(demo_page, label="←  Back to demo")

st.markdown(
    """
<div class="doc">
<p class="lead">A grounded question-answering assistant over a fixed corpus of 3GPP
specifications. It answers with an exact clause citation, or it explicitly declines.
It has no knowledge outside the corpus and never guesses.</p>

<h2>How it answers</h2>
<p>Every question runs the same path: retrieve candidate clauses, then pass three
independent gates before anything reaches you.</p>
<ol>
<li><b>Relevance gate</b> filters on raw retrieval scores. If nothing in the corpus is
about the question, it declines here with no model call.</li>
<li><b>Sufficiency gate</b> catches on-topic clauses that do not actually contain the fact
asked for, and questions about a live network that no specification can answer.</li>
<li><b>Verifiability gate</b> checks, in code, that every supporting quote appears
verbatim in the clause it cites. A fabricated quote is withheld.</li>
</ol>
<p>A refusal is a correct outcome, not a failure. The four refusal reasons are reported
separately: no relevant clause, insufficient, not answerable from the standards, and
unverifiable.</p>

<h2>The corpus</h2>
<p>Seven specifications, all pinned to a single release so a cross-specification answer
describes one coherent version of the system:</p>
<ul>
<li>TS 38.300 &middot; NR overall description</li>
<li>TS 38.321 &middot; MAC protocol</li>
<li>TS 38.322 &middot; RLC protocol</li>
<li>TS 38.323 &middot; PDCP protocol</li>
<li>TS 38.331 &middot; RRC protocol</li>
<li>TS 28.545 &middot; fault supervision</li>
<li>TS 28.552 &middot; performance measurements</li>
</ul>

<h2>How it is evaluated</h2>
<p>The evaluation set was frozen before any retrieval tuning existed, so the questions
could not be shaped to flatter the system. Answers are generated by one model and their
groundedness is judged by a different model, because a model grading its own output is
biased toward it.</p>
</div>
    """,
    unsafe_allow_html=True,
)

st.markdown('<div class="section-label">Live index</div>', unsafe_allow_html=True)
try:
    health = requests.get(f"{API}/health", timeout=10).json()
    st.markdown(
        f'<div class="stat-row">'
        f'<div class="stat"><b>{health["chunks"]:,}</b><span>Chunks indexed</span></div>'
        f'<div class="stat"><b>Release {health["release"]}</b><span>Pinned version</span></div>'
        f'<div class="stat"><b>{health["gemini_model"]}</b><span>Generation model</span></div>'
        f'</div>',
        unsafe_allow_html=True,
    )
except Exception as exc:
    st.error(f"API unreachable: {exc}")

st.markdown(
    '<p class="meta">3GPP specification text © 3GPP. Retrieved clauses are shown as cited '
    'quotations. See NOTICE.md.</p>',
    unsafe_allow_html=True,
)
